# Config for asep.py
global:
    min_na_percentage: 50
    run_flag: "new_run"  # No space is allowed

# Configs for `train` subcommand
train:
    input:
        input_file: ""
        first_k_rows: 0

    filter:
        mask_as: null
        mask_out: null
        min_group_size: 2
        max_group_size: null
        drop_cols: 
        - "log2FC"
        - "bn_p"
        - "bn_p_adj"
        - "bb_p"
        - "bb_p_adj"
        - "group_size"
        - "bn_ASE"
        - "Chrom"
        - "Pos"
        - "Ref"
        - "Alt"
        - "GeneID"
        - "FeatureID"
        - "GeneName"
        - "Intron"
        - "Exon"
        - "CCDS"
        - "motifEName"
        - "pLI_score"
        - "gnomAD_AF"
        - "EncExp"
        - "GerpN"
        response_col: "bb_ASE"

    configuration:
        random_sed: 1234
        test_size: null
        classifier: "gbc"  # Choices: abc (), gbc(gradient boosting classifier)
        nested_cv: true
        inner_cvs: 6
        inner_n_jobs: 5
        inner_n_iters: 50
        outer_cvs: 6
        with_learning_curve: false
        learning_curve_cvs: 4
        learning_curve_n_jobs: 5
        learning_curve_space_size: 10

    output:
        output_dir: "./"

# Configs for `validate` subcommand
validate:
    input:
        model_file: ""
        first_k_rows: 0

    filter:
        drop_cols: null
        response_col: "bb_ASE"

    output:
        output_dir: "./"


# Configs for `predict`
predict:
    input:
        input_file: ""
        model_file: ""

    filter:
        drop_cols: null
        first_k_rows: 0

    output:
        output_dir: null # Normally the same to the model file
