# Config for asep.py
global:
    run_flag: "new_task_from_configs_file"  # No space is allowed
    # config_file: config.yaml  # The configuration file it self
    # config_first: false  # Using configurations from config_file at high priority
    # subcmd: train # the default subcommand [train, predict, validate, config]

train: # Configs for `train` subcommand

# Input
    input_file: ""

# Filter
    first_k_rows: null
    mask_as: null
    mask_out: null
    min_group_size: 2
    max_group_size: 1.0E+5  # When using scientific notation, do NOT foget the decimal
    max_na_ratio: 0.5

## Which columns should be abundant manually: ("pLI_score", "gnomAD_AF", "EncExp", "GerpN")
    drop_cols: ["bb_p", "bb_p_adj", "bn_ASE", "bn_p", "bn_p_adj", "group_size", "log2FC", "Chrom", "Pos", "Ref", "Alt", "CCDS", "Exon", "FeatureID", "GeneID", "GeneName", "Intron", "motifEName"]
    response_col: "bb_ASE"

# Configurations
    random_sed: 1234
    # test_size: null
    classifier: "gbc"  # Choices: abc (), gbc(gradient boosting classifier)
    nested_cv: false
    inner_cvs: 6
    inner_n_jobs: 5
    inner_n_iters: 50
    outer_cvs: 6
    with_learning_curve: false
    learning_curve_cvs: 4
    learning_curve_n_jobs: 5
    learning_curve_space_size: 10

# Output
    output_dir: "./"

## How to save the model and other data to the disk. Options: [pickle, joblib]
    save_method: "pickle"  # Library used to save the model and other data set

# Configs for `validate` subcommand
validate:
# Input
    model_file: ""

# Filter
    first_k_rows: 0
    drop_cols: null
    response_col: "bb_ASE"

# Output
    output_dir: "./"

predict: # Configs for `predict`
# Input
    input_file: ""
    model_file: ""

# Filter
    first_k_rows: 0
    drop_cols: null

# Output
## Normally the same to the model file
    output_dir: null

# Configs to generate or check the sanity of given config file
config:
## The name of output config file
    output_file: "config.yaml"

## Only useful when you want to check the sanity of given config file
    config_file: "config.yaml" 
    overwrite: -1  # -1, 0, 1 ask, keep, overwrite